#!/bin/bash

f_pause(){
	read -p "$*"
}

clear
echo "install lamp stack"
sudo apt-get update -y
sudo apt-get install apache2 -y

ifconfig eth0 | grep inet | awk '{ print $2 }'

f_pause 'write down the displayed ip address and and press enter'

sudo apt-get install mysql-server -y 
sudo apt-get install libapache2-mod-auth-mysql -y
sudo apt-get install php5-mysql -y

sudo mysql_install_db

sudo /usr/bin/mysql_secure_installation

sudo apt-get install php5 -y
sudo apt-get install libapache2-mod-php5 -y
sudo apt-get install php5-mcrypt -y

echo "Add index.php to the beginning of index files. The page should now look like this:

<IfModule mod_dir.c>

          DirectoryIndex index.php index.html index.cgi index.pl index.php index.xhtml index.htm

</IfModule>"

sudo gedit /etc/apache2/mods-enabled/dir.conf

echo "<?php
phpinfo();
?>" > info.php

f_pause 'just save the file and press enter'

sudo cp ./info.php /var/www/html/info.php

sudo service apache2 restart

echo "about to install phpmyadmin do the following:"
echo "* select apache2 from the server"
echo "* choose YEs when asked about wheather to configure the datavase for phpmyadmin with dbconfig-common"
echo "* enter you MySQL password when prompted"
echo "* enter the password that you want to use to log into phpmyadmin"

f_pause 'press enter to continue'

sudo apt-get install phpmyadmin apache2-utils

sudo gedit /etc/apache2/apache2.conf

Include /etc/phpmyadmin/apache.conf

sudo service apache2 restart

echo "about to lock down phpmyadmin for security"