#!/bin/bash

f_pause(){
	read -p "$*"
}

sudo /usr/lib/nux/unity_support_test -p

echo "if you see any red no's continue by mounting the virtual box guest additions that can be downloaded from the vbox site. make sure to get the correct one coresponding with your version of virtualbox"

f_pause 'press enter once disc is mounted or CTRL+C to abort'

sudo apt-get install linux-headers-$(uname -r)
sudo apt-get autoremove
sudo apt-get install build-essential
cd /media
cd $(uname -r)
cd VBOX*
sudo ./VBoxLinuxAdditions.run

echo "add vboxvideo in the next line after lp, click save and file quit"

f_pause 'press enter when complete'

sudo gedit /etc/modules

sudo shutdown -r now
